### ISSUE TITLE
Connecting and breakpoints in callbacks

### ISSUE THREAD

**Issue by jmussman** [TheBenji/brackets-node-debugger#12]
I'm experiencing two problems, and the symptoms are the same on Windows and OS X. I'm using the current version of the extension and the current version of Brackets (1.1), which could be part of the issue.

First, I have a small test node application that is clear in the attached screen-capture. About 10% of the time if I start brackets, launch the application with --debug-brk, connect to it, and set a breakpoint in the callback it stops at the breakpoint after I step past the listen call. The rest of the time it ignores the breakpoint, but I think the problem is that the extension is miss-handling it. I have discovered that if I set the breakpoint AFTER stepping past the listen call then it works. If I restart the application and reconnect, step past the listen, and then clear and reset the breakpoint then it stops at the breakpoint. If I leave it or clear and reset it BEFORE stepping past the listen then it ignores it.

Second, about 50% of the time when I reconnect the extension window doesn't notice that it is really reconnected. Clicking the run button still works though even though it is grayed out, and I can get past the listen statement. The screen shot shows this: the red x is present instead of the green icon and it doesn't appear to be connected, but it is actually stopped at the breakpoint.

It took a while to find the reproducible sequence for the breakpoint problem, I'm sorry that I haven't had time to dig into your code, but I'd have to figure out the layout of the whole tool. But I'd like this to work, I teach Node for several well-known companies and I'd really like a debugger with breakpoints in Brackets (Theseus is nice but I can't look inside a callback). If I can give you any help let me know what I can do, but I'm betting that you will have a faster handle on where to look :)

![screen shot 2014-12-31 at 2 05 28 pm](https://cloud.githubusercontent.com/assets/6170555/5589970/3075aaea-90f8-11e4-9d08-dbf70fa45469.png)

Regards,
Joel Mussman

**Comment by TheBenji** [comment]
I uploaded an update which should at least fix the bug that it confuese sometimes the connection status.

For the breakpoint-bug, that's a little complicated:
Basically a breakpoint has two locations, one is there where you set it and one is the "actual location" for the V8 debugger itself.
In your example you set a breakpoint before the V8 engine knows about this code since you stopped it before thus it assumes the whole callback is just one line and the actual location is always line 13.

If you set the Breakpoint after you stepped over it the V8 engine understood it and sets the breakpoint at the location where you want it.

Now the debugger shows the breakpoint where it actually is (like pretty much every debugger does).
That might be sometimes a little confusing too but I guess after all a way better solution.

Try it out and let me know if that works for you!

**Comment by jmussman** [comment]
Thanks!

I'll get your changes and test it out :)

Joel Mussman
