### ISSUE TITLE
"Cannot read property 'enableDebugger' of undefined" ? Why?

### ISSUE THREAD

**Issue by 285858315** [TheBenji/brackets-node-debugger#13]
![qq 20150304171906](https://cloud.githubusercontent.com/assets/2813953/6480799/a0a37966-c292-11e4-8a42-80bc53ef43ba.png)

**Comment by TheBenji** [comment]
Hm, that shouldn't happen. Which version of Brackets are you using?

**Comment by 285858315** [comment]
Is latest.
![qq 20150304171906](https://cloud.githubusercontent.com/assets/2813953/6481066/f3762e7a-c294-11e4-9dfc-0fca06533219.png)

**Comment by TheBenji** [comment]
Actually, I believe that is the brackets debugger.
You have in the menu the "Enable Node Debugger" and at the very end you have "Node.js Debugger".
This exentsion adds just the "Node.js Debugger" and has nothing to do with the "Enable Node Debugger" - that is to debug the node backend process from Brackets and not your own Node applications :)

Your error messages seems like it would refer to the brackets debugger rather than this node.js debugger.

Can you confirm that?

**Comment by 285858315** [comment]
![qq 20150304173944](https://cloud.githubusercontent.com/assets/2813953/6481142/f49a8d54-c295-11e4-998e-efb1207efdc8.png)
![qq 20150304173944](https://cloud.githubusercontent.com/assets/2813953/6481147/ffd9f628-c295-11e4-91a5-82814f34f4aa.png)

**Comment by 285858315** [comment]
![qq 20150304173919](https://cloud.githubusercontent.com/assets/2813953/6481149/06e4dfbe-c296-11e4-9233-8215e232b76b.png)

**Comment by TheBenji** [comment]
Make sure to click on the "Node.js Debugger" entry in your menu to activate this exetension.
I get the same error if I click on "Enable Node Debugger" but that is a brackets bug and has nothing to do with this exentsion.
