### ISSUE TITLE
under ubuntu cannot connect 

### ISSUE THREAD

**Issue by ta3pks** [TheBenji/brackets-node-debugger#15]
brackets tells that max connections was reached     http://i.imgur.com/QrcADVD.png

http://i.imgur.com/EQs5rra.png

**Comment by TheBenji** [comment]
I used in on Mint which is based on ubuntu so in theory it should work although I didn't try it in some time.

Either way those connections to rhcloud are not form the debugger so that might be a different problem. But if something else throws an error it might very well be that the debugger stops working as well. Maybe try to disable all other extensions and see what happens?
